---
galaxy_info:
  author: baselines
  description: Baseline configuration for Debian Linux hosts
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Debian
      versions:
        - trixie

dependencies: []
